### ISSUE TITLE
'Cannot GET /' when excluding full path

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/node4ords#19]
The IP address of my server is 192.168.1.15. If I attempt to go to: `http://192.168.1.15/` (excluding /ords or /apex from the URL), the page simply outputs: `Cannot GET /`

![screenshot from 2015-09-23 19 16 10](https://cloud.githubusercontent.com/assets/1747643/10041449/a3762352-6227-11e5-9ca9-8c3fa0700ce6.png)

**Comment by GasparYYC** [comment]
Could someone please provide an update or ETA to dealing with this bug?
Seems like @tschf added for 0.1.0 milestone on Sep 23 2015.
This bug is preventing the tomcat from doing a redirect when the user just types: app.domain.com

thanks

**Comment by tschf** [comment]
@GasparYYC this seems to be due to missing the route (See: http://stackoverflow.com/a/21318071/3476713)

That is line 41 should be `app.get('/', function(req, res, next){` instead of `app.get(function(req, res, next){`

I've tested this a while back and it seems to resolve the issue, just lost track to add this change back to the project. I'll push it in a sec.
