### ISSUE TITLE
Example of Self Signed SSL Certificate

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/node4ords#20]
Until let's encrypt is live, create an example of self signed certificate.

**Comment by dmcghan** [comment]
Perhaps showing how to use https://www.ssls.com/user/certificates would be better? Their "PositiveSSL Multi-Domain" option would cover www.site.com and site.com for only $26 a year!

**Comment by martindsouza** [comment]
Examples below. These are just examples and haven't been vetted by a security audit.

``` bash
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -passout pass:oracle -subj "/C=CA/ST=Alberta/L=Calgary/O=Global Security/OU=IT Department/CN=localhost" -sha256

openssl rsa -in key.pem -passin pass:oracle -out newkey.pem && mv newkey.pem key.pem
```

**Comment by GasparYYC** [comment]
@martindsouza Decoding either of those {key.pem|cert.pem} gives an error like this:
unable to load X509 request
140334158399392:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: CERTIFICATE REQUEST

A .cert created via keytool decodes fine.

Update:
  I found the right commands that produces the certificate and decodes (tests) fine:
openssl req -newkey rsa:2048 -nodes -keyout example.com.key -out example.com.csr

(seems the x509 makes it unhappy)

**Comment by SERIDJ** [comment]
hi @martindsouza  @GasparYYC  ,

i want generate a self-signed certificate from an existing Private Key and CSR with : 
openssl x509 \-signkey domain.key \-in domain.csr \-req -days 365 -out domain.crt 

i have the same error ? 



![image](https://user-images.githubusercontent.com/46067255/73468493-29401b80-4385-11ea-89f4-e4d41a7ce67a.png)

**Comment by Tej-Singh-Rana** [comment]
I want to generate a self-signed certificate from a existing key and cert and when i run this command. It gives me a error any idea? what is the issue it is.
```$ openssl x509 -req -in tej.key -CA ca.crt -CAkey ca.key -CAcreateserial -out tej.crt -days 366```
```140501751308736:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE REQUEST```

**Comment by JnMik** [comment]
Seems like everybody hit this error on windows.

& $OPENSSL_EXEC_PATH x509 -req -days 3652 -in csr.txt -CA crt.txt -CAkey key.txt -CAcreateserial -out signed.txt
1124:error:0909006C:PEM routines:get_name:no start line:crypto\pem\pem_lib.c:745:Expecting: CERTIFICATE REQUEST

I'm pretty sure this command actually works on linux as I am currently migrating some code from Lin to Win.

**Comment by GasparYYC** [comment]
This is the exact command I use on CentOS:

```
[root@small tmp]# openssl req -newkey rsa:2048 -nodes -keyout example.com.key -out example.com.csr
Generating a 2048 bit RSA private key
..........+++
...+++
writing new private key to 'example.com.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:
State or Province Name (full name) []:
Locality Name (eg, city) [Default City]:
Organization Name (eg, company) [Default Company Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (eg, your name or your server's hostname) []:
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
[root@small tmp]#
```


Then I validate the files:
```
[root@small tmp]# file example.com.*
example.com.csr: PEM certificate request
example.com.key: ASCII text
[root@small tmp]#
[root@small tmp]#
[root@small tmp]# ls -l example.com.*
-rw-r--r-- 1 root root  952 Jul 10 13:36 example.com.csr
-rw-r--r-- 1 root root 1704 Jul 10 13:36 example.com.key
[root@small tmp]#

```

And IIRC just copy those files to the certs folders and thats it.
(Assuming you have the SSL definition in your webserver config)
