### ISSUE TITLE
Look at using Express Framework

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/node4ords#22]
http://www.ateam-oracle.com/oracle-jet-with-nodejs/

**Comment by dmcghan** [comment]
node4ords already uses Express (see line 1 of app.js). What are you looking to do specifically?

**Comment by martindsouza** [comment]
@dmcghan When we first started N40 I manually created the structure for everything. This ticket is more of a reminder to see what the best practices are for Express. Specifically `npm install express-generator -g` from the link above.

**Comment by martindsouza** [comment]
No change required.
